### ISSUE TITLE
todo (before merging webmap code into main ?)

### ISSUE THREAD

**Issue by turbomam** [linkml/schema-automator#5]
## @cmungall
- [x] remove all research-project specific files
- [ ] remove mentions of research-project specific files from READMEs
- [ ] move research-project specific files to their own repos
    - they're currently in a local, .gitignored folder on @turbomam 's laptop
- [ ] create tabular output in SSSOM format
    - [ ] confidence  = 1 - cosine distance between query and matched term?

### Makefile:
include a simpler example within this repo e.g
- [ ] mixs
- [x] a fake simple example

### mapping code in general
- [ ] minor: some of this belongs in git commit messages
- [x] in general no need to retain commented out code, git takes care of history
- [ ] in general most docs should go in docstrings so they are visible at IDE/RTD level
- [ ] we may want to think about a yaml config file in the future
    - (the config file would be described using linkml)
- [ ] consider using rtd to document this repo

## @wdduncan

You may want to consider 
- [ ] creating a pypi package for this
- [ ] attaching command-line utils to the package. I have examples of this in nmdc-schema.

**Comment by turbomam** [comment]
@wdduncan can you elaborate on what a CLI for the webmapping would look like? I am already using a `click` CLI.

**Comment by wdduncan** [comment]
In the [setup.py on nmdc-schema](https://github.com/microbiomedata/nmdc-schema/blob/ca2f6e0ebef7699f554a5dc2abae4e994ce61765/setup.py#L22) you will see the `validate-nmdc-json` and `nmdc-version` entry points.

This allows to run the associated python files from any directory just like other command line tools. E.g., after installing `nmdc-schema` (i.e., `pip install nmdc-schema`) you can find out the version of the schema by executing `nmdc-version`.

To accomplish the same thing with a `.py` file you need to 1) clone the repo and 2) modify your path to include the `.py` file.

**Comment by sierra-moxon** [comment]
I am going to close for now; I think a lot of this functionality is in place.  Please reopen if needed.

**Comment by amc-corey-cox** [comment]
Closing — this predates the current repo structure. All relevant items (docs, pypi, SSSOM) have been addressed. @sierra-moxon previously recommended closing.
